import "@/styles/globals.css";

import { TooltipProvider } from "@/components/ui/tooltip";
import { TRPCReactProvider } from "@/trpc/react";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable} h-full bg-gray-50`}>
			<body className="h-full">
				<TRPCReactProvider>
					<TooltipProvider delayDuration={0}>{children}</TooltipProvider>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
